// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: test_trx.proto

package test_trx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestTrxProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nonce   uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Data    []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *TestTrxProto) Reset() {
	*x = TestTrxProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_trx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTrxProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTrxProto) ProtoMessage() {}

func (x *TestTrxProto) ProtoReflect() protoreflect.Message {
	mi := &file_test_trx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTrxProto.ProtoReflect.Descriptor instead.
func (*TestTrxProto) Descriptor() ([]byte, []int) {
	return file_test_trx_proto_rawDescGZIP(), []int{0}
}

func (x *TestTrxProto) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TestTrxProto) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TestTrxProto) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_test_trx_proto protoreflect.FileDescriptor

var file_test_trx_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x54,
	0x72, 0x78, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_test_trx_proto_rawDescOnce sync.Once
	file_test_trx_proto_rawDescData = file_test_trx_proto_rawDesc
)

func file_test_trx_proto_rawDescGZIP() []byte {
	file_test_trx_proto_rawDescOnce.Do(func() {
		file_test_trx_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_trx_proto_rawDescData)
	})
	return file_test_trx_proto_rawDescData
}

var file_test_trx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_trx_proto_goTypes = []any{
	(*TestTrxProto)(nil), // 0: types.TestTrxProto
}
var file_test_trx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_trx_proto_init() }
func file_test_trx_proto_init() {
	if File_test_trx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_trx_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TestTrxProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_trx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_trx_proto_goTypes,
		DependencyIndexes: file_test_trx_proto_depIdxs,
		MessageInfos:      file_test_trx_proto_msgTypes,
	}.Build()
	File_test_trx_proto = out.File
	file_test_trx_proto_rawDesc = nil
	file_test_trx_proto_goTypes = nil
	file_test_trx_proto_depIdxs = nil
}
